# Generated by Django 5.0.6 on 2024-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'информацию',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
