# Generated by Django 5.0.6 on 2024-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnnotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
    ]
