# Generated by Django 5.0.6 on 2024-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnnotations', '0003_info_balance_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('balance', models.FloatField(verbose_name='Баланс')),
                ('percent', models.IntegerField(choices=[(2, '2%'), (4, '4%'), (10, '10%'), (16, '16%')], default=4, verbose_name='Процент на остаток')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'Накопительный счёт',
            },
        ),
    ]
