# Generated by Django 5.0.6 on 2024-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('dtime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('status', models.CharField(choices=[('new', 'Новый запрос'), ('processing', 'В обработке'), ('success', 'Обработан')], default='new', max_length=12, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'комметарий',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
